name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install packages
        run: |
          npm ci
          npm run install-all-packages
      
      - name: Run tests
        run: npm run test
